name: "Premiere Action"

on: 
  push:
    branches: "main"

jobs:
  saluer:
    runs-on: ubuntu-latest
    steps:
    - name: "Appel AKTION"
      run: cat entrypoint.sh
    - name: "Salutation"
      run: echo "Salut les DevOps ✌️"

  aurevoir:
    runs-on: windows-latest
    steps:
    - name: "Dire aurevoir"
      run: Write-Host "À la prochaine les gens"

  
    
